@PaymentService_HostAddress = https://localhost:7118

POST {{PaymentService_HostAddress}}/pay
Accept: application/json
content-type:application/json
{
  "amount": 100.0,
  "currency": "USD",
  "paymentMethod": "CreditCard"
}

###
